### ISSUE TITLE
Zemeroth port doesn't show sprites

### ISSUE THREAD

**Issue by Zireael07** [not-fl3/miniquad#29] opened 2020-02-26 12:44 UTC

**Comment by not-fl3** [comment] 2020-02-27 01:55
Thanks for the report, should be fixed now! 

https://not-fl3.github.io/miniquad-samples/zemeroth.html was broken and should works fine now. If there were other issues - feel free to reopen.

**Comment by Zireael07** [comment] 2020-02-28 09:47
Reopening, as I just got the zemeroth demo to crash... by using the alchemist's heal ability.

GL_INVALID_OPERATION
GL.recordError is not a function
    at _glGenObject (gl-0.2.20.js:1)
    at glGenBuffers (gl-0.2.20.js:1)
    at wasm-function[1384]:0xc3efd
    at wasm-function[1350]:0xc1ca5
    at wasm-function[1351]:0xc2083
    at wasm-function[905]:0x9367a
    at wasm-function[1278]:0xb733d
    at wasm-function[1668]:0xed51a
    at wasm-function[1699]:0xedebd
    at animation (gl-0.2.20.js:1)

**Comment by not-fl3** [comment] 2020-02-28 18:10
Can't reproduce :( 

Usually, the error message is just above the stack trace in the browser console - if you will find this kind of bug again - the whole console log would be helpful! 

What was your browser/OS?

**Comment by Zireael07** [comment] 2020-02-28 18:26
Brave browser (1.2.43 Chromium: 79.0.3945.130 (Official Build) unknown (64-bit) on Linux Manjaro Juhraya KDE

**Comment by Zireael07** [comment] 2020-02-28 18:41
Crashed again, this time when trying to switch units. Some sort of a memory leak/corruption?

Exact same stack as before, except under GL_INVALID_OPERATION there's a one line I missed last time: _glGenObject | @ | gl-0.2.20.js:1

**Comment by not-fl3** [comment] 2020-02-28 18:50
🤔 hmm, yes, looks like leak in `gwg`
Will try to catch it!

**Comment by not-fl3** [comment] 2020-03-14 18:28
![renderdoc](https://user-images.githubusercontent.com/910977/76687905-c2ea2200-65ed-11ea-9fc1-8ecb40a0b9d3.gif)
With the help of an in-browser profiler, I guess I fixed it!

New version: https://not-fl3.github.io/miniquad-samples/zemeroth.html

**Comment by not-fl3** [comment] 2020-03-15 20:40
Let's consider this fixed, feel free to re-open thought!

**Closed by not-fl3** 2020-03-15 20:40 UTC
